from enum import Enum

class IntentType(Enum):
    CREATE_ORDER = "CREATE_ORDER"
    LIST_ORDERS = "LIST_ORDERS"
    SEARCH_ORDER = "SEARCH_ORDER"
    UPDATE_DELIVERY_DATE = "UPDATE_DELIVERY_DATE"
    MARK_COMPLETED = "MARK_COMPLETED"
    VIEW_PENDING = "VIEW_PENDING"
    VIEW_TODAY = "VIEW_TODAY"
    VIEW_OVERDUE = "VIEW_OVERDUE"
    GENERATE_INVOICE = "GENERATE_INVOICE"
    DOWNLOAD_EXCEL = "DOWNLOAD_EXCEL"
    UNKNOWN = "UNKNOWN"
